#!/bin/bash
#
# 10 esimese paarisarvu summa
#
for (( arv=1; arv<11; arv++ )) # arvud vahemikus 1-10 
do
	jaak=$(($arv % 2)) # jagamine kahega
	if [ $jaak -eq 0 ]; then # kui jääk on null, siis
		summa=$(($summa + $arv)) #liidetakse
		echo $summa
	fi
done
echo "Arvude vahemikus 1-10 paarisarvude summa on: $summa"
#
#Lõpp
