#!/bin/bash
#
#Skript peab arvutama sisestatud arvu numbrite summat ja väljastama koos seletava tekstiga
#
echo -n "Sisesta suvaline täisarv: "
read arv
summa=0
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "Arvu numbrite summa on $summa"
#
#Lõpp
