#!/bin/bash
#
# ajaväärtuste väljastamine
#
# nädalapäev
echo -n "Täna on "
echo -n `date +"%A"`
# kuupäev
echo -n ", "
echo -n `date +"%d.%m.%Y"`
# kellaaeg
echo -n " ja kell on "
echo `date +"%H:%M"`
#
#lõpp
