#!/bin/bash
#
#
#Skript, mis küsib kasutaja käest tema nimi ja tervitab teda
#
#
echo -n "Sisesta oma ees- ja perenimi:"
read  Eesnimi Perenimi
echo "Sinu eesnimi on $Eesnimi ja perenimi on $Perenimi"
#
#
#Lõpp
