#!/bin/bash
#
#Script, mis oleks abiks bussi ekskursioonide korraldajale
#
#
echo -n "Sisesta reisijate kogus: " #sisestad reisijate koguse
read reisijad
echo -n "Kui palju on bussis istekohti?: " #sisestad istekohtade arvu
read kohad
kokku=`expr $kohad - $reisijad`
taidetud=`expr $reisijad / $kohad`
echo "100% täidetud busse on" `expr $taidetud` "maha jäi" `expr $kokku` "inimest"
#
#lõpp
#
