#!/bin/bash
#
echo -n "Sisesta ridade arv: "
read rida
echo -n "Sisesta tärnide arv reas: "
read tarn
for (( r = 1; r <= $rida; r++ ))
do
	echo -n "$r "
		if [ $r -eq 1 -o $r -eq $rida ]; then
			for (( t = 1; t <= $tarn; t++ ))
		do
			echo -n "* "
done
else
echo -n "* "
	for (( t = 2; t < $tarn; t++ ))
		do
	 		echo -n "  "
		done
			echo -n "* "
		fi
	echo
done

